### ISSUE TITLE
ask: its complete icon set, but depends

### ISSUE THREAD

**Issue by mckaygerhard** [tsujan/Plataro#1]
i culd see that this icon set are qt related, so all the sizes must be defined.. so 

as i can see, its same install from git  _ i dont see that INSTALL instruction where updated in a while..

**Comment by tsujan** [comment]
This is a salable icon set and sizes are defined in `index.theme`: each icon is used for all sizes (for now).

The installation is explained in the file `INSTALL`.

**Comment by mckaygerhard** [comment]
i saw!, well i'll try and write some feedback .. due where sizes are not all complete break the qt integration..  i'll close this issue later when comes feedback..

**Comment by tsujan** [comment]
I use it with KDE and LXQt without problem. Actually, I made it for Qt, not GTK+

**Comment by mckaygerhard** [comment]
i tested, are a complete set due all the sizes are computed dinamically (its very heavy under low profile machines)

how its the it depends on either Oxygen or GNOME icon theme, whichever is installed, .. its seems rely firs on gnome-puach set and then oxigen if both are installed..

close it:
![plataro-gambas](https://user-images.githubusercontent.com/1571724/29523590-83d3eda4-865b-11e7-9e99-6058a3d70694.png)

**Comment by tsujan** [comment]
If an icon isn't found, it'll first search in Oxygen, then in Gnome and, at last, in hicolor. As a matter of fact, the Qt plugin does that. KDE and LXQt have their Qt plugins but in other DE's, you should install one.

**Comment by mckaygerhard** [comment]
ah! ok, so the problem its that i not are in a "proper"2 desktop yet, i just run openbox... thanks.. good work.

**Comment by tsujan** [comment]
You need a Qt plugin. The best one I know of is `lxqt-qtplugin`. Then you could set the environment variable `QT_QPA_PLATFORMTHEME` to `lxqt` in any DE -- you won't need LXQt.

Another option is `qt5ct` but it has some bugs.

**Comment by mckaygerhard** [comment]
please tell me why qt5ct are buggy, its was that i thinking unless you mention lxqt-qtplugin

**Comment by tsujan** [comment]
It isn't "buggy"; it just has minor bugs, some of which may have been fixed. I know about this one, for example: https://github.com/tsujan/Kvantum/issues/148

2 years ago, I found other bugs in it too but they weren't important and may not exist anymore.

**Comment by tsujan** [comment]
Anyhow, lxqt-qtplugin works like a charm.
