### ISSUE TITLE
Update firefox icon to v57 or newer

### ISSUE THREAD

**Issue by Mad-Soft** [tsujan/Plataro#2]
You can use actual icon for firefox-esr and new icon for firefox
[firefox.zip](https://github.com/tsujan/Plataro/files/1729701/firefox.zip)

Thanks for you work and giving us these beautiful icons

**Comment by tsujan** [comment]
You're welcome!

> You can use actual icon for firefox-esr and new icon for firefox

I had edited the classic firefox icon. I think all people recognize it as a mildly flattened  firefox ;)

Since, most of the time, there's only one installed firefox, there's no need to distinguish between `firefox-esr.svg` and `firefox.svg`; hence the symlink.
