### ISSUE TITLE
Request Icons

### ISSUE THREAD

**Issue by EliaHKM** [tsujan/Plataro#3]
Hi,
Could you please add icons for these apps 
Brave [https://brave.com/](url)
Fredi  [https://getferdi.com/](url)
keepassxc [https://flathub.org/apps/details/org.keepassxc.KeePassXC](url)
equate [https://git.enlightenment.org/apps/equate.git](url)
flatseal [https://flathub.org/apps/details/com.github.tchx84.Flatseal](url)
Oomox [https://flathub.org/apps/details/com.github.themix_project.Oomox](url)
Element [https://flathub.org/apps/details/im.riot.Riot](url)
qjoypad and antimcrox [https://flathub.org/apps/details/io.github.antimicrox.antimicrox](url)
Metadata Cleaner [https://flathub.org/apps/details/fr.romainvigier.MetadataCleaner](url)
Dialect [https://flathub.org/apps/details/com.github.gi_lom.dialect](url)
Pcsx2 [https://flathub.org/apps/details/net.pcsx2.PCSX2](url)
Persepolis [https://persepolisdm.github.io/](url)
Rage [https://download.enlightenment.org/rel/apps/rage/rage-0.3.1.tar.xz](url)
ppsspp [https://www.ppsspp.org/](url)
Ecrire [https://github.com/Obsidian-StudiosInc/ecrire](url)
ephoto [https://download.enlightenment.org/rel/apps/ephoto/ephoto-1.5.tar.xz](url)
gpick
Thanks in advance 
peace ✌

**Comment by tsujan** [comment]
Hi,

Thanks for the suggestions!

I'm afraid my free time is mostly taken by programming. Once in a while, I may add some non-app icons or polish some icons but there are two many apps and Plataro is more or less compatible with their default icons.

Sorry that I have to close this! Your request was quite acceptable and valid; I might use your list if I find more time but I don't think that'll happen soon.
